site_name: SoYeah Documntation
site_url: https://soyeah42.github.io/Documents/
site_description: SoYeah Help Me Center
site_author: Mechanic


theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

  features:
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - navigation.top
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share


  #logo: assets/SoYeahLogo.png
  favicon: assets/SoYeahLogo.png

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets

extra:
  social:
    - icon: fontawesome/brands/youtube 
      link: https://youtube.com/@james-willett
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/willettjames
  copyright: Copyright &copy; 2025 SoYeah

plugins:
  - search
 # - awesome-pages

nav:
  - Home: index.md
  - User Guide:
    - SoYeah Reach: 
      - Getting Started: getting-started.md
      - Features: features.md
    - Writing your docs: writing-your-docs.md
    - Styling your docs: styling-your-docs.md
  - About:
    - License: license.md
    - Release Notes: release-notes.md

extra_css:
  - assets/custom.css 
